In [1]:
import random
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import warnings
import statistics 
import numpy as np
from matplotlib import rcParams
from concurrent.futures import ProcessPoolExecutor
from datetime import datetime


rcParams['figure.figsize'] = 15,8

warnings.filterwarnings('ignore')

today = datetime.now()
todays_date = today.strftime("%Y-%m-%d")

In [2]:
from crypto_backtesting import get_bitcoin_data
crypto_df = get_bitcoin_data(years=[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023])
crypto_df['price'] = crypto_df['open'] # set open to be the price to use 
crypto_df

,timestamp,open,high,low,close,volume,Datetime,quarter,price
0,2014-01-01 00:00:00,739.2800,739.2800,739.2800,739.2800,1.500000e-01,2014-01-01 00:00:00,1,739.2800
1,2014-01-01 01:00:00,742.9989,742.9989,742.9989,742.9989,3.720000e+00,2014-01-01 01:00:00,1,742.9989
2,2014-01-01 02:00:00,748.4900,748.8900,748.4900,748.8900,5.740000e+00,2014-01-01 02:00:00,1,748.4900
3,2014-01-01 03:00:00,740.0000,743.1000,740.0000,740.0000,2.256364e+00,2014-01-01 03:00:00,1,740.0000
4,2014-01-01 04:00:00,745.3100,745.3100,745.3100,745.3100,1.745600e+00,2014-01-01 04:00:00,1,745.3100
...,...,...,...,...,...,...,...,...,...
80036,2023-02-17 20:00:00,24523.0000,25023.0000,24523.0000,24834.0000,1.012941e+07,2023-02-17 20:00:00,37,24523.0000
80037,2023-02-17 21:00:00,24833.0000,24841.0000,24426.0000,24495.0000,4.186570e+06,2023-02-17 21:00:00,37,24833.0000
80038,2023-02-17 22:00:00,24479.0000,24745.0000,24057.0000,24692.0000,5.983257e+06,2023-02-17 22:00:00,37,24479.0000
80039,2023-02-17 23:00:00,24687.0000,24745.0000,24525.0000,24582.0000,1.484912e+06,2023-02-17 23:00:00,37,24687.0000
80040,2023-02-18 00:00:00,24580.0000,24790.0000,24553.0000,24655.0000,3.599322e+05,2023-02-18 00:00:00,37,24580.0000

In [3]:
from crypto_backtesting import run_multiple_backtests

#Run all the combinations we want to look at 
strategies = ["mean reversion", "simple moving average crossover"]
shorting_settings = [True, False]

for strategy in strategies:
    for shorting in shorting_settings:
        result_df = run_multiple_backtests(
            shorting_allowed=shorting,
            num_runs=100,
            fixed_fee=False,
            crypto_df=crypto_df,
            strategy=strategy
        )
        shorting_str = "shorting" if shorting else "no_shorting"
        filename = f"run_output/{strategy.replace(' ', '_')}_{shorting_str}_{todays_date}.csv"
        result_df.to_csv(filename)